services:
  backend:
    build: ../backend
    container_name: fastapi-ant-demo-backend
    restart: always
    environment:
      APP_ENV: prod
    volumes:
      - ../config/config.yaml:/app/config.yaml:ro
    ports:
      - "8000:8000"
    networks:
      - ops-net

  frontend:
    build:
      context: ../frontend
      args:
        VITE_API_BASE_URL: /api/v1
    container_name: fastapi-ant-demo-frontend
    restart: always
    ports:
      - "8083:80"
    depends_on:
      - backend
    networks:
      - ops-net

networks:
  ops-net:
    driver: bridge
